"""
ExplainX pipeline refinement + multi-scene renderer.

Improves the existing pipeline (no new phases, no narration/subtitles):
  * Multi-scene breakdown per topic (Task 1/6)
  * Multiple assets/diagrams across scenes (Task 1)
  * Cinematic shot variety per scene via smooth camera (Task 2/3)
  * Dynamic per-scene duration (Task 5)
  * Per-phase timing + saved outputs + quality report (Task 9/10/11)

Run from backend/:

    python refine_pipeline.py "Planet Earth"
    python refine_pipeline.py "Photosynthesis"
    python refine_pipeline.py "Human Heart"
    python refine_pipeline.py --all
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import time
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from animation import TimelineEngine  # noqa: E402
from scene_generation import SceneEngine  # noqa: E402
from scene_generation.scene_duration import (  # noqa: E402
    classify_complexity,
    estimate_scene_duration,
)
from scene_generation.scene_metadata import SceneLayout, SceneSpec, SceneType  # noqa: E402
from scene_generation.scene_templates import get_fixture  # noqa: E402
from video_renderer import TimelinePlayer, encode_video  # noqa: E402
from video_renderer.ffmpeg_encoder import SubprocessFFmpegExecutor  # noqa: E402


# --------------------------------------------------------------------------- #
# Concept breakdowns — multi-scene storytelling (Question → Explain → Recap).
# --------------------------------------------------------------------------- #

def _scene(title, subtitle, bullets, *, scene_type=SceneType.SINGLE_CONCEPT,
           layout=SceneLayout.HERO, shot="medium"):
    return {
        "title": title,
        "subtitle": subtitle,
        "bullets": bullets,
        "scene_type": scene_type,
        "layout": layout,
        "shot": shot,
    }


TOPIC_SCENES: dict[str, list[dict[str, Any]]] = {
    "planet earth": [
        _scene("Planet Earth", "What makes Earth unique?",
               ["Third planet from the Sun", "Only known world with life", "71% covered by water"],
               layout=SceneLayout.HERO, shot="wide"),
        _scene("Earth's Layers", "A world built in shells",
               ["Crust", "Mantle", "Outer core", "Inner core"],
               scene_type=SceneType.SINGLE_CONCEPT, layout=SceneLayout.LEFT_ILLUSTRATION, shot="zoom"),
        _scene("The Atmosphere", "The protective blanket of air",
               ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"],
               layout=SceneLayout.RIGHT_ILLUSTRATION, shot="medium"),
        _scene("Magnetic Field", "The invisible shield",
               ["Generated by the molten core", "Deflects solar wind", "Creates the auroras"],
               layout=SceneLayout.HERO, shot="detail"),
        _scene("Recap: Planet Earth", "Putting it together",
               ["Layered internal structure", "Protective atmosphere", "Dynamic magnetic field"],
               layout=SceneLayout.CENTERED, shot="summary"),
    ],
    "photosynthesis": [
        _scene("Photosynthesis", "How do plants make food?",
               ["Occurs in green plants", "Converts light into energy", "Foundation of the food chain"],
               scene_type=SceneType.PROCESS, layout=SceneLayout.LEFT_ILLUSTRATION, shot="wide"),
        _scene("The Inputs", "What plants take in",
               ["Sunlight", "Water (H₂O)", "Carbon dioxide (CO₂)"],
               scene_type=SceneType.PROCESS, layout=SceneLayout.LEFT_ILLUSTRATION, shot="zoom"),
        _scene("The Process", "Inside the chloroplast",
               ["Light reactions capture energy", "Calvin cycle builds sugar", "Chlorophyll absorbs light"],
               scene_type=SceneType.PROCESS, layout=SceneLayout.RIGHT_ILLUSTRATION, shot="detail"),
        _scene("The Outputs", "What plants release",
               ["Glucose for energy", "Oxygen into the air"],
               scene_type=SceneType.PROCESS, layout=SceneLayout.LEFT_ILLUSTRATION, shot="medium"),
        _scene("Recap: Photosynthesis", "The energy equation",
               ["Light + CO₂ + H₂O", "→ Glucose", "→ Oxygen released"],
               layout=SceneLayout.CENTERED, shot="summary"),
    ],
    "human heart": [
        _scene("The Human Heart", "The engine of circulation",
               ["A muscular pump", "Beats ~100,000 times a day", "Four chambers"],
               scene_type=SceneType.SPLIT_VIEW, layout=SceneLayout.LEFT_ILLUSTRATION, shot="wide"),
        _scene("The Chambers", "Four rooms of the heart",
               ["Left atrium", "Right atrium", "Left ventricle", "Right ventricle"],
               scene_type=SceneType.SPLIT_VIEW, layout=SceneLayout.LEFT_ILLUSTRATION, shot="zoom"),
        _scene("The Valves", "One-way doors",
               ["Mitral valve", "Tricuspid valve", "Aortic & pulmonary valves"],
               layout=SceneLayout.RIGHT_ILLUSTRATION, shot="detail"),
        _scene("Blood Flow", "The double loop",
               ["Body → right heart → lungs", "Lungs → left heart → body", "A continuous cycle"],
               scene_type=SceneType.PROCESS, layout=SceneLayout.LEFT_ILLUSTRATION, shot="medium"),
        _scene("Recap: The Heart", "Why it matters",
               ["Four chambers", "One-way valves", "Double circulation"],
               layout=SceneLayout.CENTERED, shot="summary"),
    ],
}

# Cinematic shot → target zoom (clamped to 1.00–1.10).
SHOT_ZOOM = {"wide": 1.0, "medium": 1.04, "zoom": 1.07, "detail": 1.10, "summary": 1.03}

BASE_FIXTURE = {
    "planet earth": "earth",
    "photosynthesis": "photosynthesis",
    "human heart": "human heart",
}


def _slug(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in name.strip()).strip("_") or "topic"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _size(path: Path | None) -> int:
    if not path or not Path(path).is_file():
        return 0
    return Path(path).stat().st_size


def _fmt_size(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KB"
    return f"{n / (1024 * 1024):.2f} MB"


def _find_illustration(topic: str, keyword: str | None = None) -> Path | None:
    needles = [topic.lower().split()[0]]
    if keyword:
        needles.insert(0, keyword.lower())
    for folder in (ROOT / "processed_assets", ROOT / "generated" / "raw", ROOT / "raw_assets"):
        if not folder.is_dir():
            continue
        for path in sorted(folder.iterdir()):
            if path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
                continue
            low = path.name.lower()
            if any(n in low for n in needles):
                return path
    return None


def _placeholder(path: Path, label: str) -> Path:
    img = Image.new("RGBA", (640, 640), (238, 243, 248, 255))
    draw = ImageDraw.Draw(img)
    draw.ellipse((120, 120, 520, 520), fill=(176, 200, 222, 255), outline=(70, 100, 135, 255), width=4)
    draw.text((210, 300), label[:16], fill=(30, 45, 70, 255))
    img.save(path)
    return path


class Timer:
    def __init__(self) -> None:
        self.rows: list[dict[str, Any]] = []

    def record(self, phase: str, ms: float, out: str = "", size: int = 0) -> None:
        self.rows.append({"phase": phase, "ms": round(ms, 2), "output": out, "size": size})

    @property
    def total_ms(self) -> float:
        return round(sum(r["ms"] for r in self.rows), 2)


class TopicResult:
    def __init__(self, topic: str) -> None:
        self.topic = topic
        self.scenes: list[dict[str, Any]] = []
        self.assets_used: set[str] = set()
        self.diagram_count = 0
        self.frame_count = 0
        self.timeline_events = 0
        self.camera_events = 0
        self.animation_count = 0
        self.total_duration = 0.0
        self.fps = 30
        self.videos: list[str] = []
        self.ok = True
        self.failures: list[str] = []


def _dirs(topic_root: Path) -> dict[str, Path]:
    names = ["raw", "scripts", "images", "diagrams", "scenes", "timelines", "frames", "videos", "logs"]
    out = {}
    for n in names:
        d = topic_root / n
        d.mkdir(parents=True, exist_ok=True)
        out[n] = d
    return out


def run_topic(topic: str, *, ffmpeg_ok: bool, log: list[str]) -> TopicResult:
    key = topic.strip().lower()
    concepts = TOPIC_SCENES.get(key)
    if concepts is None:
        raise ValueError(f"No concept breakdown for topic: {topic}")

    result = TopicResult(topic)
    topic_root = ROOT / "output" / "refined" / _slug(topic)
    if topic_root.exists():
        shutil.rmtree(topic_root, ignore_errors=True)
    d = _dirs(topic_root)
    timer = Timer()

    def emit(msg: str) -> None:
        line = f"{datetime.now().isoformat(timespec='seconds')} | {msg}"
        log.append(line)
        print(msg, flush=True)

    emit("=" * 64)
    emit(f"TOPIC: {topic}  ({len(concepts)} scenes)")
    emit("=" * 64)

    # Phase: raw content + deterministic script outline (no narration/subtitles).
    t0 = time.perf_counter()
    raw_doc = {"topic": topic, "concepts": concepts, "created_at": _now()}
    (d["raw"] / "content.json").write_text(json.dumps(raw_doc, indent=2, default=str), encoding="utf-8")
    script_lines = [f"# {topic} — Scene Outline", ""]
    for i, c in enumerate(concepts, 1):
        script_lines.append(f"## Scene {i}: {c['title']}")
        script_lines.append(f"_{c['subtitle']}_")
        for b in c["bullets"]:
            script_lines.append(f"- {b}")
        script_lines.append("")
    (d["scripts"] / "script.md").write_text("\n".join(script_lines), encoding="utf-8")
    timer.record("content+script", (time.perf_counter() - t0) * 1000, str(d["scripts"] / "script.md"))

    base_illustration = _find_illustration(topic) or _placeholder(
        d["images"] / f"{_slug(topic)}_base.png", topic
    )

    scene_engine = SceneEngine()
    timeline_engine = TimelineEngine()
    player = TimelinePlayer()

    for idx, concept in enumerate(concepts, 1):
        scene_tag = f"scene_{idx:02d}"
        emit("")
        emit(f"[{scene_tag}] {concept['title']} — shot={concept['shot']}")

        # ---- Multi-asset resolution (Task 1) ---------------------------------
        t0 = time.perf_counter()
        keyword = concept["title"].split()[0]
        illustration = _find_illustration(topic, keyword=keyword) or base_illustration
        result.assets_used.add(str(illustration))
        img_copy = d["images"] / f"{scene_tag}{Path(illustration).suffix}"
        if not img_copy.exists():
            try:
                shutil.copy2(illustration, img_copy)
            except OSError:
                img_copy = illustration
        timer.record(f"{scene_tag}:image", (time.perf_counter() - t0) * 1000, str(img_copy), _size(img_copy))

        # ---- Dynamic duration (Task 5) --------------------------------------
        duration = estimate_scene_duration(
            bullet_count=len(concept["bullets"]),
            asset_count=1,
            diagram_count=1,
        )

        # ---- Scene compose (+ diagram) (Task 1/8) ---------------------------
        t0 = time.perf_counter()
        base_spec = get_fixture(BASE_FIXTURE.get(key, "earth")) or get_fixture("earth")
        spec = replace(
            base_spec,
            title=concept["title"],
            subtitle=concept["subtitle"],
            bullets=list(concept["bullets"]),
            scene_type=concept["scene_type"],
            layout=concept["layout"],
            scene_number=idx,
            duration_seconds=duration,
            illustration_path=str(illustration),
        )
        scene_dir = d["scenes"] / scene_tag
        scene_result = scene_engine.compose(spec, output_dir=scene_dir, compose_diagram=True)
        scene_json = scene_result.metadata.to_dict()
        scene_json["bullets"] = list(concept["bullets"])
        scene_json["footer"] = f"ExplainX · {topic}"
        # Shot variety via constrained target zoom (Task 2/3).
        scene_json.setdefault("camera", {})
        scene_json["camera"]["zoom"] = SHOT_ZOOM.get(concept["shot"], 1.06)
        diagrams = scene_json.get("diagrams") or []
        result.diagram_count += len(diagrams)
        timer.record(
            f"{scene_tag}:scene",
            (time.perf_counter() - t0) * 1000,
            scene_result.json_path or str(scene_dir),
            _size(Path(scene_result.png_path) if scene_result.png_path else None),
        )

        # ---- Animation timeline (Task 4/8) ----------------------------------
        t0 = time.perf_counter()
        tl_dir = d["timelines"] / scene_tag
        tl = timeline_engine.build_from_scene(scene_json, output_dir=tl_dir)
        animation_json = json.loads(Path(tl.animation_path).read_text(encoding="utf-8"))
        result.animation_count += len(animation_json.get("animations", []))
        result.camera_events += len(animation_json.get("camera_events", []))
        result.timeline_events += len((scene_json.get("timeline") or {}).get("elements", []))
        timer.record(f"{scene_tag}:timeline", (time.perf_counter() - t0) * 1000, tl.animation_path or "")

        # ---- Playback → frames (Task 8) -------------------------------------
        t0 = time.perf_counter()
        fps = int(animation_json.get("fps", 30))
        result.fps = fps
        frames_dir = d["frames"] / scene_tag
        playback = player.play_timeline(
            scene_json, animation_json, output_dir=frames_dir, fps=fps
        )
        result.frame_count += playback.exported_count
        result.total_duration += duration
        timer.record(
            f"{scene_tag}:frames",
            (time.perf_counter() - t0) * 1000,
            playback.output_directory,
            0,
        )

        expected_frames = int(round(duration * fps))
        if abs(playback.exported_count - expected_frames) > fps:  # allow <1s tolerance
            result.ok = False
            result.failures.append(
                f"{scene_tag}: frame count {playback.exported_count} vs expected ~{expected_frames}"
            )

        # ---- Video encode (Task 8/12) ---------------------------------------
        scene_info: dict[str, Any] = {
            "scene": scene_tag,
            "title": concept["title"],
            "duration": duration,
            "frames": playback.exported_count,
            "expected_frames": expected_frames,
            "diagrams": len(diagrams),
            "shot": concept["shot"],
            "zoom": scene_json["camera"]["zoom"],
        }
        if ffmpeg_ok:
            t0 = time.perf_counter()
            video_dir = d["videos"] / scene_tag
            try:
                vmeta = encode_video(
                    playback.output_directory,
                    fps=playback.fps,
                    output_format="mp4",
                    profile="standard",
                    playback_metadata=playback,
                    scene_metadata=scene_json,
                    output_dir=video_dir,
                )
                playable = bool(vmeta.mp4_path and _size(Path(vmeta.mp4_path)) > 800)
                scene_info.update(
                    {
                        "video": vmeta.mp4_path,
                        "video_size": _size(Path(vmeta.mp4_path)) if vmeta.mp4_path else 0,
                        "codec": vmeta.codec,
                        "resolution": list(vmeta.resolution),
                        "playable": playable,
                    }
                )
                if vmeta.mp4_path:
                    result.videos.append(vmeta.mp4_path)
                if not playable:
                    result.ok = False
                    result.failures.append(f"{scene_tag}: MP4 not playable")
                timer.record(
                    f"{scene_tag}:encode",
                    (time.perf_counter() - t0) * 1000,
                    vmeta.mp4_path or "",
                    scene_info.get("video_size", 0),
                )
            except Exception as exc:  # noqa: BLE001
                result.ok = False
                result.failures.append(f"{scene_tag}: encode failed — {exc}")
                emit(f"  ENCODE FAILED: {exc}")
        else:
            scene_info["playable"] = False
            result.ok = False
            result.failures.append("FFmpeg not available")

        result.scenes.append(scene_info)
        emit(
            f"  duration={duration}s frames={playback.exported_count} "
            f"diagrams={len(diagrams)} zoom={scene_json['camera']['zoom']}"
        )

    _write_quality_report(topic_root, result, timer)
    (d["logs"] / "run.log").write_text("\n".join(log), encoding="utf-8")
    _write_timing_csv(d["logs"] / "timing.csv", timer)

    _print_topic_summary(result, timer, topic_root, emit)
    return result


def _write_timing_csv(path: Path, timer: Timer) -> None:
    import csv

    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["phase", "execution_ms", "output", "size_bytes"])
        for r in timer.rows:
            w.writerow([r["phase"], r["ms"], r["output"], r["size"]])
        w.writerow(["TOTAL", timer.total_ms, "", ""])


def _write_quality_report(topic_root: Path, result: TopicResult, timer: Timer) -> None:
    complexity = classify_complexity(result.total_duration)
    avg_fps = result.fps
    lines = [
        f"# Quality Report — {result.topic}",
        "",
        f"Generated: {_now()}",
        "",
        "## Summary",
        "",
        f"- **Scenes**: {len(result.scenes)}",
        f"- **Generated assets used**: {len(result.assets_used)}",
        f"- **Diagrams**: {result.diagram_count}",
        f"- **Rendered frames**: {result.frame_count}",
        f"- **Video duration**: {round(result.total_duration, 2)} s ({complexity})",
        f"- **Average FPS**: {avg_fps}",
        f"- **Timeline events**: {result.timeline_events}",
        f"- **Camera events**: {result.camera_events}",
        f"- **Animation count**: {result.animation_count}",
        f"- **Total pipeline time**: {timer.total_ms} ms",
        "",
        "## Scenes",
        "",
        "| # | Title | Shot | Zoom | Duration | Frames | Diagrams | Playable |",
        "|---|-------|------|------|----------|--------|----------|----------|",
    ]
    for i, s in enumerate(result.scenes, 1):
        lines.append(
            f"| {i} | {s['title']} | {s.get('shot','')} | {s.get('zoom','')} | "
            f"{s['duration']}s | {s['frames']} | {s['diagrams']} | "
            f"{'YES' if s.get('playable') else 'NO'} |"
        )
    lines += ["", "## Assets used", ""]
    for a in sorted(result.assets_used):
        lines.append(f"- `{a}`")
    if result.failures:
        lines += ["", "## Issues", ""]
        for f in result.failures:
            lines.append(f"- {f}")
    lines += ["", f"**Status**: {'PASS' if result.ok else 'FAIL'}", ""]
    (topic_root / "quality_report.md").write_text("\n".join(lines), encoding="utf-8")


def _print_topic_summary(result: TopicResult, timer: Timer, topic_root: Path, emit) -> None:
    emit("")
    emit("-" * 64)
    emit(f"PIPELINE TIMING — {result.topic}")
    emit("-" * 64)
    for r in timer.rows:
        size = f" ({_fmt_size(r['size'])})" if r["size"] else ""
        emit(f"  {r['phase']:<22} {r['ms']:>9.2f} ms{size}")
    emit(f"  {'TOTAL':<22} {timer.total_ms:>9.2f} ms")
    emit("")
    emit(f"  Scenes:        {len(result.scenes)}")
    emit(f"  Assets used:   {len(result.assets_used)}")
    emit(f"  Diagrams:      {result.diagram_count}")
    emit(f"  Frames:        {result.frame_count}")
    emit(f"  Duration:      {round(result.total_duration, 2)} s")
    emit(f"  Camera events: {result.camera_events}")
    emit(f"  Animations:    {result.animation_count}")
    emit(f"  Output:        {topic_root}")
    emit(f"  Report:        {topic_root / 'quality_report.md'}")


def main() -> int:
    """Deprecated — delegates to the stabilized ``build_video.py`` pipeline."""
    import warnings
    warnings.warn(
        "refine_pipeline.py is deprecated; use build_video.py for single-MP4 output",
        DeprecationWarning,
        stacklevel=1,
    )
    from build_video import main as stabilized_main
    return stabilized_main()


def _legacy_main() -> int:
    parser = argparse.ArgumentParser(description="ExplainX multi-scene pipeline refinement")
    parser.add_argument("topic", nargs="?", default="Planet Earth")
    parser.add_argument("--all", action="store_true", help="Run Earth, Photosynthesis, Human Heart")
    args = parser.parse_args()

    ffmpeg_ok = SubprocessFFmpegExecutor().is_available()
    if not ffmpeg_ok:
        print("WARNING: FFmpeg not found on PATH — videos will not be encoded.", flush=True)

    topics = ["Planet Earth", "Photosynthesis", "Human Heart"] if args.all else [args.topic]

    print("=" * 64)
    print("EXPLAINX PIPELINE REFINEMENT")
    print("=" * 64)

    results: list[TopicResult] = []
    for topic in topics:
        log: list[str] = []
        try:
            results.append(run_topic(topic, ffmpeg_ok=ffmpeg_ok, log=log))
        except Exception as exc:  # noqa: BLE001
            import traceback

            print(f"FAILED {topic}: {exc}")
            traceback.print_exc()
            r = TopicResult(topic)
            r.ok = False
            r.failures.append(str(exc))
            results.append(r)

    print("")
    print("=" * 64)
    print("VERIFICATION")
    print("=" * 64)
    all_ok = True
    for r in results:
        checks = {
            "multiple_scenes": len(r.scenes) >= 2,
            "multiple_assets": len(r.assets_used) >= 1 and r.diagram_count >= 2,
            "frames_rendered": r.frame_count > 0,
            "dynamic_duration": r.total_duration > 15.0,
            "playable_mp4": ffmpeg_ok and all(s.get("playable") for s in r.scenes) and bool(r.scenes),
            "no_failures": not r.failures,
        }
        ok = all(checks.values())
        all_ok = all_ok and ok
        print(f"\n{r.topic}: {'PASS' if ok else 'FAIL'}")
        for name, val in checks.items():
            print(f"  {'✓' if val else '✗'} {name}")
        for f in r.failures:
            print(f"    - {f}")

    print("")
    if all_ok and ffmpeg_ok:
        print("EXPLAINX PIPELINE VERIFIED")
        return 0
    print("EXPLAINX PIPELINE NOT VERIFIED — see checks above")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
