"""Multi-layer cache protocols — independently invalidatable."""

from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID

from asset_intelligence.schemas.asset import AssetRecord
from asset_intelligence.schemas.concept import ConceptGraphSnapshot, ConceptNode
from asset_intelligence.schemas.prompt import GenerationResult, PromptBundle
from asset_intelligence.schemas.style import StyleProfile


@runtime_checkable
class ConceptCacheProtocol(Protocol):
    def get(self, key: str) -> ConceptNode | ConceptGraphSnapshot | None: ...
    def put(self, key: str, value: ConceptNode | ConceptGraphSnapshot) -> None: ...
    def invalidate(self, key: str | None = None) -> None: ...


@runtime_checkable
class AssetCacheProtocol(Protocol):
    def get_by_hash(self, content_hash: str) -> AssetRecord | None: ...
    def get_by_id(self, asset_id: UUID) -> AssetRecord | None: ...
    def put(self, record: AssetRecord) -> None: ...
    def invalidate(self, key: str | UUID | None = None) -> None: ...


@runtime_checkable
class PromptCacheProtocol(Protocol):
    def get(self, key: str) -> PromptBundle | None: ...
    def put(self, key: str, prompt: PromptBundle) -> None: ...
    def invalidate(self, key: str | None = None) -> None: ...


@runtime_checkable
class StyleCacheProtocol(Protocol):
    def get(self, style_id: str) -> StyleProfile | None: ...
    def put(self, profile: StyleProfile) -> None: ...
    def invalidate(self, style_id: str | None = None) -> None: ...


@runtime_checkable
class GenerationCacheProtocol(Protocol):
    def get(self, prompt_hash: str) -> GenerationResult | None: ...
    def put(self, prompt_hash: str, result: GenerationResult) -> None: ...
    def invalidate(self, key: str | None = None) -> None: ...
